CREATE USER replicator WITH REPLICATION PASSWORD 'qal1h2j3khCu7';
GRANT pg_monitor to replicator;

CREATE DATABASE longblueroad;
CREATE USER regular WITH LOGIN PASSWORD '123456';
GRANT ALL PRIVILEGES ON DATABASE longblueroad TO regular;

\c longblueroad

GRANT ALL PRIVILEGES ON SCHEMA public TO regular;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO regular;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO regular;

CREATE TABLE road (id SERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, length INT NOT NULL);
CREATE TABLE cafe (id SERIAL PRIMARY KEY, name TEXT NOT NULL, road_id INTEGER REFERENCES road(id));
