CREATE TABLE road (id SERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, length INT NOT NULL);
CREATE INDEX ON road(name) TABLESPACE ispace;
CREATE ROLE driver LOGIN PASSWORD 'AZCVoi172e9A&CV981';
GRANT CONNECT ON DATABASE longblueroad TO driver;
GRANT INSERT ON TABLE road TO driver;
GRANT USAGE, SELECT ON SEQUENCE road_id_seq TO driver;
