/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.part3.Person;
import org.example.part3.Place;
import org.example.part3.Robot;

public class App {
    public static void main(String[] args) {
        Place room = new Place("room", 5,  5);
        Robot robot = new Robot();
        Person trillian = new Person("Trillian", 28);

        System.out.println(robot.standup());
        System.out.println(robot.walkAcross(room));
        System.out.println(robot.stopInFrontOf(trillian));
        System.out.println(robot.lookAt(trillian));
    }
}
